proyecto-semestral-creepy-2-final v7.1/creepypastaprueba2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('usuarios/', include('usuarios.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


proyecto-semestral-creepy-2-final v7.1/paginas/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', inicio, name="inicio"),
    path('historias/<slug:idcreepypasta>', historias, name="historias"),
    path('informacion/', informacion, name="informacion"),
    path('logueate/', logueate, name="logueate"),
    path('listadom/', listadom, name="listadom"),
    path('registro/', registro, name="registro"),
    path('subircreepy/', subircreepy, name="subircreepy"),
    path('tushistorias/', tushistorias, name="tushistorias"),
    path('vermensajesadmi/', vermensajesadmi, name="vermensajesadmi"),
    path('enviarmensajeadmi/', enviarmensajeadmi, name="enviarmensajeadmi"),
    path('registraM/', registraM, name="registraM"),
    path('registraMEN/', registraMEN, name="registraMEN"),
    path('eliminarcreepy/<codigos>', eliminarcreepy, name="eliminarcreepy"),
    path('eliminarcreepy1/<codigos1>', eliminarcreepy1, name="eliminarcreepy1"),
    path('borrarmensajes/<id>', borrarmensajes, name="borrarmensajes"),
    path('borrarusuario/<ide>', borrarusuario, name="borrarusuario"),
    path('borrarcomentarios/<idees>', borrarcomentarios, name="borrarcomentarios"),

    path('usuario/<usuario>', cargar_usuario, name='cargar_usuario'),
    path('megusta/<idcreepypasta>', añadir_megusta, name='añadir_megusta'),
    path('agregar_comentario/<idcreepypasta>', agregar_comentario, name='agregar_comentario'),
    path('verusuariosadmi/', verusuariosadmi, name="verusuariosadmi"),
    path('ajustedatos/<ides>', ajustedatos, name="ajustedatos"),
    path('ajustescomentarios/<ideees>', ajustescomentarios, name="ajustescomentarios"),


     


]

proyecto-semestral-creepy-2-final v7.1/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    path('registrar/', views.registrar, name='registrar'),
    path('iniciar/', views.iniciar, name='iniciar'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
]

proyecto-semestral-creepy-2-final v7.1/paginas/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Genero(models.Model):
    idgenero = models.AutoField(primary_key=True,verbose_name="ID autoincrementable del genero")
    genero = models.CharField(max_length=30, verbose_name="Genero del creepy")

    def __str__(self):
        return self.genero

class CreepyPasta(models.Model):
    idcreepypasta = models.AutoField(verbose_name="id del creepypasta", primary_key=True)
    resumen = models.TextField()
    nombrecreepy = models.CharField(verbose_name="Nombre del creepypasta", max_length=20)
    historia = models.TextField(verbose_name="Historia")
    imagen = models.ImageField(upload_to="creepypastas")
    generos = models.ForeignKey(Genero,on_delete=models.CASCADE)
    creador = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='paginas_historia', null=True
    )
    me_gusta = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    
    def __str__(self):
        return self.nombrecreepy
    
    def get_absolute_url(self):
        return reverse("historias", args=[str(self.idcreepypasta)])
    
    def agregar_megusta(self):
        return reverse("añadir_megusta", args=[str(self.idcreepypasta)])
    
    @property
    def obtener_comentarios(self):
        comentarios = Comentario.objects.filter(creepy=self)
        return comentarios

class MensajesAdmi2(models.Model):
    idmensaje = models.AutoField(verbose_name="id del mensaje", primary_key=True)
    mensaje = models.TextField(verbose_name="Nmensaje del admi")
    consultasadmi = models.CharField(verbose_name="tipo consulta", max_length=20)
    #agregar un campo usuario al modelo
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE , null=True)

    def __str__(self):
        return self.mensaje


class Comentario(models.Model):
    idcomentario = models.AutoField(verbose_name="id del comentario", primary_key=True)
    creepy = models.ForeignKey(CreepyPasta, on_delete=models.CASCADE, related_name='comentarios', null=True)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cuerpo = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.usuario}-{self.cuerpo}'

proyecto-semestral-creepy-2-final v7.1/usuarios/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


class AdministradorUsuarios(BaseUserManager):
    def create_user(self, correo, primer_nombre, apellido, password, **other_fields):

        if not correo:
            raise ValueError(_('Debes ingresar un email valido'))

        correo = self.normalize_email(correo)
        user = self.model(correo=correo, primer_nombre=primer_nombre,
                          apellido=apellido, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, correo, primer_nombre, apellido, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Super usuario debe debe tener valor is_staff "True"')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Super usuario debe debe tener valor is_superuser "True"')

        return self.create_user(correo, primer_nombre, apellido, password, **other_fields)


class Usuario(AbstractBaseUser, PermissionsMixin):
    correo = models.EmailField(_('dirección de correo'), unique=True)
    primer_nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    imagen_perfil = models.ImageField(
        upload_to='usuarios/', default='usuarios/predeterminada.jpg')

    slug = models.SlugField(max_length=255, unique=True)
    nacimiento = models.DateTimeField(default=timezone.now)
    fecha_registro = models.DateTimeField(default=timezone.now)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    USERNAME_FIELD = 'correo'
    REQUIRED_FIELDS = ['primer_nombre', 'apellido']
    objects = AdministradorUsuarios()

    def __str__(self):
        return f'{self.primer_nombre} {self.apellido}'

    def get_absolute_url(self):
        return reverse('usuarios:usuario_detalle', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.correo)
        super(Usuario, self).save(*args, **kwargs)

proyecto-semestral-creepy-2-final v7.1/usuarios/forms.py
from dataclasses import fields
from django import forms
from usuarios.models import Usuario
from paginas.models import Comentario
#from paginas.models import Usuario

class usuariosForm(forms.ModelForm):

    primer_nombre = forms.CharField(min_length=3,max_length=9)
    apellido = forms.CharField(min_length=3,max_length=9)
    correo = forms.EmailField(min_length=14,max_length=30)

    class Meta:
        model = Usuario
        fields = ["primer_nombre","apellido","correo"]
    

class comentarioForm(forms.ModelForm):


    class Meta:
        model = Comentario
        fields = ["cuerpo"]



proyecto-semestral-creepy-2-final v7.1/paginas/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from usuarios.models import Usuario
from usuarios.forms import usuariosForm , comentarioForm

from .models import Comentario, CreepyPasta, Genero, MensajesAdmi2


def inicio(request):
    return render(request, 'paginas/inicio.html')

@login_required(login_url='logueate')
def ajustedatos(request,ides):
    datos1 = Usuario.objects.get(correo = ides)
    datos = {
        'form': usuariosForm(instance=datos1)
    }
    if request.method== 'POST':
        formulario = usuariosForm(data=request.POST,instance=datos1)
        if formulario.is_valid:
            formulario.save()
            return redirect(to="tushistorias")

    return render(request, 'paginas/ajustecuenta.html',datos)


@login_required(login_url='logueate')
def ajustescomentarios(request,ideees):
    datos2 = Comentario.objects.get(idcomentario = ideees)
    datos = {
        'form1': comentarioForm(instance=datos2)
    }
    if request.method== 'POST':
        formulario = comentarioForm(data=request.POST,instance=datos2)
        if formulario.is_valid:
            formulario.save()
            return redirect(to="inicio")

    return render(request, 'paginas/ajustecomentarios.html',datos)




def informacion(request):
    return render(request, 'paginas/informacion.html')


def logueate(request):
    return render(request, 'paginas/logueate.html')


def registro(request):
    return render(request, 'paginas/registrate.html')



def historias(request, idcreepypasta):
    creepy = get_object_or_404(CreepyPasta, idcreepypasta=idcreepypasta)
    return render(request, 'paginas/historia1.html', {'creepy': creepy})


@permission_required('is_staff', login_url="inicio")
def borrarcomentarios(request, idees):

    borrarUS = Comentario.objects.get(idcomentario=idees)
    borrarUS.delete()

    return redirect(to="inicio")



@permission_required('is_staff', login_url="inicio")
def listadom(request):
    creepypasta1 = CreepyPasta.objects.all()
    contexto = {"lista": creepypasta1}
    return render(request, 'paginas/menuadmi.html', contexto)

@login_required(login_url='logueate')
def subircreepy(request):
    generos = Genero.objects.all()
    contexto = {"lista_r": generos}
    return render(request, 'paginas/subircreepy.html', contexto)


def registraM(request):
    imagen2 = request.FILES['imagencreepy']
    nombrec = request.POST['nombrecreepycrear']
    resumen1 = request.POST['resumencreepy']
    historia1 = request.POST['historiacreepy']
    genero2 = request.POST['seleccion1']
    genero3 = Genero.objects.get(idgenero=genero2)

    CreepyPasta.objects.create(imagen=imagen2, nombrecreepy=nombrec, creador=request.user,
                               resumen=resumen1, historia=historia1, generos=genero3)

    return redirect('subircreepy')


def inicio(request):
    inicios = CreepyPasta.objects.all()
    contexto = {"listo": inicios}
    return render(request, 'paginas/inicio.html', contexto)


 #esto es un recorador para hacer una vista privada que requiera login
@login_required(login_url='logueate')
def tushistorias(request):
    #para que solo se vean los creepi del usuario logueado pongo el filter (creador = reqyet.user)
    
    tushistorias1 = CreepyPasta.objects.filter(creador = request.user)
    contexto = {"listos": tushistorias1}
    return render(request, 'paginas/tuscreepy.html', contexto)

@permission_required('is_staff', login_url="inicio")
def verusuariosadmi(request):
    usuariomenu = Usuario.objects.all()
    contexto = {"listas2": usuariomenu}
    return render(request, 'paginas/usuariomenuadmi.html', contexto)



@permission_required('is_staff', login_url="inicio")
def vermensajesadmi(request):
    mensajes = MensajesAdmi2.objects.all()
    contexto = {"listas": mensajes}
    return render(request, 'paginas/vermensajesadmi.html', contexto)



@login_required(login_url='logueate')
def enviarmensajeadmi(request):
    return render(request, 'paginas/veryenviarmensajesaadmi.html')


def registraMEN(request):
    mensajes3 = request.POST['mensajecreepy']
    usuario = request.user
    consulta3 = request.POST['motivocreepycrear']
    #esto agrega el usuario al objeto creado
    MensajesAdmi2.objects.create(mensaje=mensajes3, consultasadmi=consulta3, usuario = usuario)

    return redirect('enviarmensajeadmi')


def eliminarcreepy(request, codigos):

    borrar = CreepyPasta.objects.get(idcreepypasta=codigos)
    borrar.delete()

    return redirect(to="listadom")

def eliminarcreepy1(request, codigos1):

    borrar = CreepyPasta.objects.get(idcreepypasta=codigos1)
    borrar.delete()

    return redirect(to="tushistorias")


def borrarusuario(request, ide):

    borrarUS = Usuario.objects.get(correo=ide)
    borrarUS.delete()

    return redirect(to="verusuariosadmi")



    


def borrarmensajes(request, id):
    borrarmensaje = MensajesAdmi2.objects.get(idmensaje=id)
    borrarmensaje.delete()
    return redirect(to="vermensajesadmi")


@login_required(login_url='logueate')
def añadir_megusta(request, idcreepypasta):
    creepy = get_object_or_404(CreepyPasta, idcreepypasta=idcreepypasta)
    if request.user in creepy.me_gusta.all():
        creepy.me_gusta.remove(request.user)
    else:
        creepy.me_gusta.add(request.user)
    creepy.save()
    return redirect(to='inicio')


@login_required(login_url='logueate')
def agregar_comentario(request, idcreepypasta):
    usuario = request.user
    creepy = get_object_or_404(CreepyPasta, idcreepypasta=idcreepypasta)
    cuerpo = request.POST["comentario"]
    comentario = Comentario(creepy=creepy, usuario=usuario, cuerpo=cuerpo)
    comentario.save()
    return redirect('historias', idcreepypasta=idcreepypasta)


def cargar_usuario(request, usuario):
    usuario = get_object_or_404(Usuario, correo=usuario)
    creepys_usuairo = CreepyPasta.objects.filter(creador=usuario)
    contexto = {"usuario": usuario, "creepys": creepys_usuairo}
    return render(request, 'paginas/usuario.html', contexto)

proyecto-semestral-creepy-2-final v7.1/usuarios/views.py
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.hashers import make_password
from django.shortcuts import redirect


def registrar(request):
    imagen = request.FILES['imagenperfil']
    nombre = request.POST["nombreregistro"]
    apellido = request.POST["apellidoregistro"]
    correo = request.POST["correoregistro"]
    contraseña = request.POST["confirmarcontraseñaregistro"]
    nacimiento1 = request.POST["edad"]
    get_user_model().objects.create(correo=correo, primer_nombre=nombre,
                                    apellido=apellido, imagen_perfil=imagen, password=make_password(contraseña),nacimiento = nacimiento1)
    return redirect(to='logueate')


def iniciar(request):
    correo = request.GET["correorelogin"]
    contraseña = request.GET["contraseñalogin"]
    usuario = authenticate(request, correo=correo, password=contraseña)
    if usuario is not None:
        login(request, usuario)
        return redirect(to='inicio')
    return redirect(to="logueate")


def cerrar_sesion(request):
    logout(request)
    return redirect('inicio')


proyecto-semestral-creepy-2-final v7.1/paginas/templates/paginas/ajustecomentarios.html
{% extends "./base.html" %}{% load static %}

{% block content %}

<head>
  <title>AJUSTE DE DATOS</title>
</head>

<body class="body1">



  <div id="section1" class=" container centrado espaciado">

    <div style="margin-top: 20%; margin-bottom: 5%;">

      <div class="col-md-2 hidden-sm"></div>

      <div class="creepyborderegistro letrasajustecuenta col-md-8 col-sm-12 ">

      <form action="" method="post" id="formularioAC" class="espaciado">
        {% csrf_token %}
        
        <div class="form-group">
          {{ form1 }}

        </div>


        <div class="espaciado">
        <input type="submit" class="btn btn-danger" id="enviar" value="MODIFICAR">
        <input type="reset" class="btn btn-danger" id="enviar" value="LIMPIAR">
        </div>
       
     

      </form>

    </div>
    <div class="col-md-2 hidden-sm"></div>



    </div>
  </div>


  <script src="{%static 'paginas/js/validacionajusdatos.js'%}"></script>

</body>
{% endblock %}








proyecto-semestral-creepy-2-final v7.1/paginas/templates/paginas/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{%static 'paginas/css/estilos.css'%}" />
</head>


<body class="body1">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'inicio' %}"><img
          src="{% static 'paginas/img/logo bajo menu/creepypasta_logo_fit.png' %}" class="logo_menu" alt="logo" /></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto centrado">
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'inicio' %}">INICIO</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'informacion' %}">INFORMACIÓN</a>
          </li>
          <li class="nav-item dropdown d-flex navbar-nav centrado">
            {% if user.correo %}
            <a class="nav-link dropdown-toggle text-danger" href="#" role="button" data-bs-toggle="dropdown">CUENTA
            </a>
            {% endif %}
            <ul class="dropdown-menu">
              <li>
                <!-- esto es una condicional para que muestre el boton solo si el usuario esta logueado-->
                {% if user.correo %}
                <a class="dropdown-item text-danger" href="{% url 'tushistorias' %}">TUS HISTORIAS</a>
                {% endif %}
              </li>
              {% if perms.catalog.is_staff %}
              <li>
                <a class="dropdown-item text-danger" href="{% url 'listadom' %}">COSAS ADMI</a>
              </li>
              {% endif %}
              <li>
                <a class="dropdown-item text-danger" href="{% url 'inicio' %}">CERRAR SESIÓN</a>
              </li>
            </ul>
          </li>
        </ul>

        <ul class="nav justify-content-end navbar-nav centrado">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'usuarios:cerrar_sesion' %}">CERRAR</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'logueate' %}">ACCEDER</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'registro' %}">REGISTRO</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div>{% block content %} {% endblock %}</div>
</body>

proyecto-semestral-creepy-2-final v7.1/paginas/templates/paginas/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{%static 'paginas/css/estilos.css'%}" />
</head>


<body class="body2">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'inicio' %}"><img
          src="{% static 'paginas/img/logo bajo menu/creepypasta_logo_fit.png' %}" class="logo_menu" alt="logo" /></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto centrado">
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'inicio' %}">INICIO</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'informacion' %}">INFORMACIÓN</a>
          </li>
          <li class="nav-item dropdown d-flex navbar-nav centrado">
            {% if user.correo %}
            <a class="nav-link dropdown-toggle text-danger" href="#" role="button" data-bs-toggle="dropdown">CUENTA
            </a>
            {% endif %}
            <ul class="dropdown-menu">
              <li>
                <!-- esto es una condicional para que muestre el boton solo si el usuario esta logueado-->
                {% if user.correo %}
                <a class="dropdown-item text-danger" href="{% url 'tushistorias' %}">TUS HISTORIAS</a>
                {% endif %}
              </li>
              {% if perms.catalog.is_staff %}
              <li>
                <a class="dropdown-item text-danger" href="{% url 'listadom' %}">COSAS ADMI</a>
              </li>
              {% endif %}
              <li>
                <a class="dropdown-item text-danger" href="{% url 'inicio' %}">CERRAR SESIÓN</a>
              </li>
            </ul>
          </li>
        </ul>

        <ul class="nav justify-content-end navbar-nav centrado">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'usuarios:cerrar_sesion' %}">CERRAR</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'logueate' %}">ACCEDER</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-danger" href="{% url 'registro' %}">REGISTRO</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div>{% block content %} {% endblock %}</div>
</body>

proyecto-semestral-creepy-2-final v7.1/paginas/templates/paginas/inicio.html
{% extends "./base.html" %} {% load static %}

{% block content %}
<head>
  <title>INICIO</title>
</head>

<body class="body1">
  <div class="container centrado espaciado" style="margin-top: 8%; margin-bottom: 3%; ">
    

    <div class="row col-md-12 espaciado">
      <div class="input-field col-md-1"></div>
      <div class=" creepybordeinicio col-md-10 letrasinicio">
        <H4>
        ( EN ESTE SITIO PODRA VER LOS CREEPYPASTAS SUBIDOS POR TODOS LOS DEMAS USUARIOS )  
        </H4>
      </div>
      <div class="input-field col-md-1"></div>
    </div>
   

    <div class="row espaciado centrado letrasinicio">
      <!--PRIMERA CREEPY-->
      {% for m in listo %}
      <div class="col-sm-6 col-md-4 centrado espaciado">
        <div class="card creepybordeinicio">
          <div class="card-body">
            <h5 class="card-title text-center">
              {% if m.imagen %}
              <img src="{{ m.imagen.url }}" alt="Sin foto " id="img_arre" />
              {% endif %}
            </h5>
            <h3 class="centrado">Nombre: <br> {{ m.nombrecreepy }}</h3>
            <h5 class="centrad">Genero: {{ m.generos }}</h5>
            <p class="centrado">{{ m.resumen }}</p>
            <h6 class="centrado"><a href="{% url 'cargar_usuario' m.creador.correo %}">{{ m.creador }}</a></h6>
            <p class="card-text text-righf">
              <a
                class="btn btn-dark"
                href="{{ m.get_absolute_url }}"
                role="button"
                >LEER AHORA</a
              >
              <a
                type="button"
                href="{{ m.agregar_megusta }}"
                class="fs-5 text-reset like-button"
              >
                {% if user in m.me_gusta.all %}
                <i class="fas fa-heart text-danger"></i>
                {% else%}
                <i class="far fa-heart"></i>
                {% endif %}
              </a>
              <span>{{m.me_gusta.all | length}}</span>
            </p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</body>
{% endblock %}

proyecto-semestral-creepy-2-final v7.1/paginas/templates/paginas/logueate.html
{% extends "./base2.html" %}{% load static %}

{% block content %}
<head>
  <title>LOGIN</title>
</head>

<body class="body2">

  <div class=" container centrado">

    <div class="row" style="margin-top: 17%; margin-bottom: 7%;">
      <div class="col-md-2 hidden-sm"></div>
      <div class="col-md-8 col-sm-12  creepybordeloginsubida">
        <form action="{% url 'usuarios:iniciar' %}" id="login1" name="logininicio" enctype="multipart/form-data">
          {% csrf_token %}
          <h1 class="centrado letrasregistroylogin">Inicio de sesión</h1>
          <div class="row letrasregistroylogin">

            <div class="form-group col-md-12 col-sm-12">
              <label>
                <h4>Ingrese su correo Electronico</h4>
              </label>
              <input type="email" id="logincorreo" name="correorelogin" class="form-control" required>
            </div>



            <div class="form-group col-md-12 col-sm-12">
              <label>
                <h4>Ingrese su contraseña</h4>
              </label>
              <input type="password" id="contraseñalogin" name="contraseñalogin" class="form-control" required>
            </div>


            <div class="col-md-3 col-sm-3 "></div>
            <div class="row espaciado col-md-6 col-sm-6 ">
              <input type="reset" class="btn btn-danger">
            </div>
            <div class="col-md-3 col-sm-3"></div>

            <div class="col-md-3  col-sm-3"></div>
            <div class="row espaciado col-md-6 col-sm-6 ">
              <button class="btn btn-danger" type="submit">
                <h5>Iniciar seccion</h5>
              </button>
            </div>
            <div class="col-md-3 col-sm-3 "></div>

            <p id="mensajes"></p>

            <h3 style="color: rgb(255, 0, 0);">PD:Por seguridad no le comparta a nadie estos datos </h3>

          </div>
        </form>
      </div>
      <div class="col-md-2 hidden-sm"></div>
    </div>

  </div>


  <script src="{%static 'paginas/js/validacionlogin.js'%}"></script>
  


</body>

{% endblock %}